package com.xiben.pm.md.mapper;

import com.xiben.pm.md.bean.MdEmployeeEx;
import com.xiben.pm.md.pojo.MdCompanyMember;
import com.xiben.pm.md.pojo.MdCompanyMemberExample;
import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface MdCompanyMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_company_member
     *
     * @mbggenerated Tue Nov 14 10:38:23 CST 2017
     */
    int countByExample(MdCompanyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_company_member
     *
     * @mbggenerated Tue Nov 14 10:38:23 CST 2017
     */
    int deleteByExample(MdCompanyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_company_member
     *
     * @mbggenerated Tue Nov 14 10:38:23 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_company_member
     *
     * @mbggenerated Tue Nov 14 10:38:23 CST 2017
     */
    int insert(MdCompanyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_company_member
     *
     * @mbggenerated Tue Nov 14 10:38:23 CST 2017
     */
    int insertSelective(MdCompanyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_company_member
     *
     * @mbggenerated Tue Nov 14 10:38:23 CST 2017
     */
    List<MdCompanyMember> selectByExample(MdCompanyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_company_member
     *
     * @mbggenerated Tue Nov 14 10:38:23 CST 2017
     */
    MdCompanyMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_company_member
     *
     * @mbggenerated Tue Nov 14 10:38:23 CST 2017
     */
    int updateByExampleSelective(@Param("record") MdCompanyMember record, @Param("example") MdCompanyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_company_member
     *
     * @mbggenerated Tue Nov 14 10:38:23 CST 2017
     */
    int updateByExample(@Param("record") MdCompanyMember record, @Param("example") MdCompanyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_company_member
     *
     * @mbggenerated Tue Nov 14 10:38:23 CST 2017
     */
    int updateByPrimaryKeySelective(MdCompanyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_company_member
     *
     * @mbggenerated Tue Nov 14 10:38:23 CST 2017
     */
    int updateByPrimaryKey(MdCompanyMember record);

	List<MdCompanyMember> queryManagerByComIdAndUserId(@Param("userId")Integer userId, @Param("companyId")Integer companyId);

	Integer isRoot(@Param("userId")Integer userId, @Param("companyId")Integer companyId);

	List<MdEmployeeEx> queryManager(@Param("companyId") Integer companyid);

	MdCompanyMember queryByUseridAndCompanyid(@Param("userId")Integer userId, @Param("companyId")Integer companyId);

	@Delete("delete from md_company_member where  userid=#{mgrUserid,jdbcType=INTEGER} and companyid=#{companyid,jdbcType=INTEGER} and role=2")
	int deleteByUserid( @Param("mgrUserid") Integer mgrUserid,@Param("companyid")Integer companyid);

	@Select("select * from md_company_member a where a.companyid =#{companyid,jdbcType=INTEGER}")
	List<MdCompanyMember> getManager(@Param("companyid")Integer companyid);
}