package com.xiben.pm.md.mapper;

import com.xiben.pm.md.pojo.MdConfig;
import com.xiben.pm.md.pojo.MdConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface MdConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_config
     *
     * @mbggenerated Mon Nov 20 09:18:44 CST 2017
     */
    int countByExample(MdConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_config
     *
     * @mbggenerated Mon Nov 20 09:18:44 CST 2017
     */
    int deleteByExample(MdConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_config
     *
     * @mbggenerated Mon Nov 20 09:18:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_config
     *
     * @mbggenerated Mon Nov 20 09:18:44 CST 2017
     */
    int insert(MdConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_config
     *
     * @mbggenerated Mon Nov 20 09:18:44 CST 2017
     */
    int insertSelective(MdConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_config
     *
     * @mbggenerated Mon Nov 20 09:18:44 CST 2017
     */
    List<MdConfig> selectByExample(MdConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_config
     *
     * @mbggenerated Mon Nov 20 09:18:44 CST 2017
     */
    MdConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_config
     *
     * @mbggenerated Mon Nov 20 09:18:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") MdConfig record, @Param("example") MdConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_config
     *
     * @mbggenerated Mon Nov 20 09:18:44 CST 2017
     */
    int updateByExample(@Param("record") MdConfig record, @Param("example") MdConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_config
     *
     * @mbggenerated Mon Nov 20 09:18:44 CST 2017
     */
    int updateByPrimaryKeySelective(MdConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_config
     *
     * @mbggenerated Mon Nov 20 09:18:44 CST 2017
     */
    int updateByPrimaryKey(MdConfig record);

    @Select("select a.`value` from md_config a where a.`code`=#{code_,jdbcType=VARCHAR}")
	String getValue(@Param("code_")String code);
}