package com.xiben.pm.md.mapper;

import com.xiben.pm.md.bean.MdDeptEx;
import com.xiben.pm.md.pojo.MdDepartment;
import com.xiben.pm.md.pojo.MdDepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

public interface MdDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department
     *
     * @mbggenerated Wed Nov 15 13:26:36 CST 2017
     */
    int countByExample(MdDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department
     *
     * @mbggenerated Wed Nov 15 13:26:36 CST 2017
     */
    int deleteByExample(MdDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department
     *
     * @mbggenerated Wed Nov 15 13:26:36 CST 2017
     */
    int deleteByPrimaryKey(Integer deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department
     *
     * @mbggenerated Wed Nov 15 13:26:36 CST 2017
     */
    int insert(MdDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department
     *
     * @mbggenerated Wed Nov 15 13:26:36 CST 2017
     */
    int insertSelective(MdDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department
     *
     * @mbggenerated Wed Nov 15 13:26:36 CST 2017
     */
    List<MdDepartment> selectByExample(MdDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department
     *
     * @mbggenerated Wed Nov 15 13:26:36 CST 2017
     */
    MdDepartment selectByPrimaryKey(Integer deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department
     *
     * @mbggenerated Wed Nov 15 13:26:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") MdDepartment record, @Param("example") MdDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department
     *
     * @mbggenerated Wed Nov 15 13:26:36 CST 2017
     */
    int updateByExample(@Param("record") MdDepartment record, @Param("example") MdDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department
     *
     * @mbggenerated Wed Nov 15 13:26:36 CST 2017
     */
    int updateByPrimaryKeySelective(MdDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department
     *
     * @mbggenerated Wed Nov 15 13:26:36 CST 2017
     */
    int updateByPrimaryKey(MdDepartment record);

	List<MdDeptEx> getMdDeptExForCompany(@Param("companyid") Integer companyid);

	List<MdDepartment> getDetpByUser(@Param("userid") Integer userid);

	@Update("update md_department set isdelete=1 where isdelete=0 and deptid=#{deptid,jdbcType=INTEGER}")
	int updateForDelete(@Param("deptid")Integer deptid);
}