package com.xiben.pm.md.mapper;

import com.xiben.pm.md.bean.MdEmployeeEx;
import com.xiben.pm.md.pojo.MdDepartmentMember;
import com.xiben.pm.md.pojo.MdDepartmentMemberExample;
import com.xiben.pm.md.pojo.MdEmployeeEntity;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface MdDepartmentMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department_member
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    int countByExample(MdDepartmentMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department_member
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    int deleteByExample(MdDepartmentMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department_member
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department_member
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    int insert(MdDepartmentMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department_member
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    int insertSelective(MdDepartmentMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department_member
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    List<MdDepartmentMember> selectByExample(MdDepartmentMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department_member
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    MdDepartmentMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department_member
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    int updateByExampleSelective(@Param("record") MdDepartmentMember record, @Param("example") MdDepartmentMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department_member
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    int updateByExample(@Param("record") MdDepartmentMember record, @Param("example") MdDepartmentMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department_member
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    int updateByPrimaryKeySelective(MdDepartmentMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_department_member
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    int updateByPrimaryKey(MdDepartmentMember record);

   
	MdDepartmentMember getMemberByUseridAndDeptid(@Param("userid")Integer userid, @Param("deptid")Integer deptid);

	List<MdEmployeeEntity> getDeptManagerByDeptid(@Param("deptid")Integer deptid);

	List<MdEmployeeEx> getMemeberList(@Param("deptid")Integer deptid);

	@Delete("delete from md_department_member where deptid=#{deptid,jdbcType=INTEGER} and memberid=#{removeuserid,jdbcType=INTEGER}")
	void deleteByMemeberid(@Param("removeuserid")Integer removeuserid,@Param("deptid")Integer deptid);

	
}