package com.xiben.pm.md.mapper;

import com.xiben.pm.md.pojo.MdDeptduty;
import com.xiben.pm.md.pojo.MdDeptdutyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MdDeptdutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_deptduty
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    int countByExample(MdDeptdutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_deptduty
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    int deleteByExample(MdDeptdutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_deptduty
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    int deleteByPrimaryKey(Integer dutyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_deptduty
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    int insert(MdDeptduty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_deptduty
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    int insertSelective(MdDeptduty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_deptduty
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    List<MdDeptduty> selectByExample(MdDeptdutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_deptduty
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    MdDeptduty selectByPrimaryKey(Integer dutyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_deptduty
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") MdDeptduty record, @Param("example") MdDeptdutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_deptduty
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    int updateByExample(@Param("record") MdDeptduty record, @Param("example") MdDeptdutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_deptduty
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    int updateByPrimaryKeySelective(MdDeptduty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_deptduty
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    int updateByPrimaryKey(MdDeptduty record);
    @Select("select * from md_deptduty a where a.deptid=#{deptid,jdbcType=INTEGER} and a.isdelete =0")
	List<MdDeptduty> queryAllDutyByDeptid(@Param("deptid")Integer deptid);

    @Update("update md_deptduty set isdelete=1 where deptid=#{deptid,jdbcType=INTEGER}")
	void updateForDelete(@Param("deptid")Integer deptid);

    @Select("select * from md_deptduty a where a.dutytype=1 and a.deptid=#{deptid,jdbcType=INTEGER}")
	MdDeptduty getDutyBydeptidwithtype1(@Param("deptid")Integer deptid);
}