package com.xiben.pm.md.mapper;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.xiben.pm.md.pojo.MdEmployeeEntity;


public interface MdEmployeeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_employee
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_employee
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    int insert(MdEmployeeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_employee
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    int insertSelective(MdEmployeeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_employee
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    MdEmployeeEntity selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_employee
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    int updateByPrimaryKeySelective(MdEmployeeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_employee
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    int updateByPrimaryKey(MdEmployeeEntity record);

	MdEmployeeEntity queryByPhone(@Param("mgrphone")String mgrphone);
}