package com.xiben.pm.md.pojo;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class MdCompany implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_company.companyid
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    private Integer companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_company.fullname
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_company.shortname
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    private String shortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_company.logo
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_company.shortnamespell
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    private String shortnamespell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_company.createby
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_company.createdate
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_company.updateby
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_company.updatedate
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_company.companyid
     *
     * @return the value of md_company.companyid
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_company.companyid
     *
     * @param companyid the value for md_company.companyid
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_company.fullname
     *
     * @return the value of md_company.fullname
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_company.fullname
     *
     * @param fullname the value for md_company.fullname
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_company.shortname
     *
     * @return the value of md_company.shortname
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_company.shortname
     *
     * @param shortname the value for md_company.shortname
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_company.logo
     *
     * @return the value of md_company.logo
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_company.logo
     *
     * @param logo the value for md_company.logo
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_company.shortnamespell
     *
     * @return the value of md_company.shortnamespell
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public String getShortnamespell() {
        return shortnamespell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_company.shortnamespell
     *
     * @param shortnamespell the value for md_company.shortnamespell
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public void setShortnamespell(String shortnamespell) {
        this.shortnamespell = shortnamespell == null ? null : shortnamespell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_company.createby
     *
     * @return the value of md_company.createby
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_company.createby
     *
     * @param createby the value for md_company.createby
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_company.createdate
     *
     * @return the value of md_company.createdate
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_company.createdate
     *
     * @param createdate the value for md_company.createdate
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_company.updateby
     *
     * @return the value of md_company.updateby
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_company.updateby
     *
     * @param updateby the value for md_company.updateby
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_company.updatedate
     *
     * @return the value of md_company.updatedate
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_company.updatedate
     *
     * @param updatedate the value for md_company.updatedate
     *
     * @mbggenerated Mon Nov 13 10:25:03 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

	@Override
	public String toString() {
		 return ReflectionToStringBuilder.toString(this); 
	}
    
}