package com.xiben.pm.md.pojo;

import java.util.Date;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class MdDeptduty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_deptduty.dutyid
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    private Integer dutyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_deptduty.compid
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    private Integer compid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_deptduty.deptid
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_deptduty.dutyname
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    private String dutyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_deptduty.remark
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_deptduty.ratio
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    private Integer ratio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_deptduty.dutytype
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    private Integer dutytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_deptduty.isdelete
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_deptduty.createby
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_deptduty.createdate
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_deptduty.updateby
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_deptduty.updatedate
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_deptduty.dutyid
     *
     * @return the value of md_deptduty.dutyid
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public Integer getDutyid() {
        return dutyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_deptduty.dutyid
     *
     * @param dutyid the value for md_deptduty.dutyid
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public void setDutyid(Integer dutyid) {
        this.dutyid = dutyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_deptduty.compid
     *
     * @return the value of md_deptduty.compid
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public Integer getCompid() {
        return compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_deptduty.compid
     *
     * @param compid the value for md_deptduty.compid
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public void setCompid(Integer compid) {
        this.compid = compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_deptduty.deptid
     *
     * @return the value of md_deptduty.deptid
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_deptduty.deptid
     *
     * @param deptid the value for md_deptduty.deptid
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_deptduty.dutyname
     *
     * @return the value of md_deptduty.dutyname
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public String getDutyname() {
        return dutyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_deptduty.dutyname
     *
     * @param dutyname the value for md_deptduty.dutyname
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public void setDutyname(String dutyname) {
        this.dutyname = dutyname == null ? null : dutyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_deptduty.remark
     *
     * @return the value of md_deptduty.remark
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_deptduty.remark
     *
     * @param remark the value for md_deptduty.remark
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_deptduty.ratio
     *
     * @return the value of md_deptduty.ratio
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public Integer getRatio() {
        return ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_deptduty.ratio
     *
     * @param ratio the value for md_deptduty.ratio
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public void setRatio(Integer ratio) {
        this.ratio = ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_deptduty.dutytype
     *
     * @return the value of md_deptduty.dutytype
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public Integer getDutytype() {
        return dutytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_deptduty.dutytype
     *
     * @param dutytype the value for md_deptduty.dutytype
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public void setDutytype(Integer dutytype) {
        this.dutytype = dutytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_deptduty.isdelete
     *
     * @return the value of md_deptduty.isdelete
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_deptduty.isdelete
     *
     * @param isdelete the value for md_deptduty.isdelete
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_deptduty.createby
     *
     * @return the value of md_deptduty.createby
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_deptduty.createby
     *
     * @param createby the value for md_deptduty.createby
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_deptduty.createdate
     *
     * @return the value of md_deptduty.createdate
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_deptduty.createdate
     *
     * @param createdate the value for md_deptduty.createdate
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_deptduty.updateby
     *
     * @return the value of md_deptduty.updateby
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_deptduty.updateby
     *
     * @param updateby the value for md_deptduty.updateby
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_deptduty.updatedate
     *
     * @return the value of md_deptduty.updatedate
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_deptduty.updatedate
     *
     * @param updatedate the value for md_deptduty.updatedate
     *
     * @mbggenerated Thu Nov 16 13:25:39 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
    
    @Override
	public String toString() {
		 return ReflectionToStringBuilder.toString(this); 
	}
}