package com.xiben.pm.md.pojo;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class MdDepartmentMember implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_department_member.id
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_department_member.compid
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    private Integer compid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_department_member.deptid
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_department_member.memberid
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    private Integer memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_department_member.deptrole
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    private Integer deptrole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_department_member.createby
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_department_member.createdate
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_department_member.updateby
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_department_member.updatedate
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_department_member.id
     *
     * @return the value of md_department_member.id
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_department_member.id
     *
     * @param id the value for md_department_member.id
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_department_member.compid
     *
     * @return the value of md_department_member.compid
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public Integer getCompid() {
        return compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_department_member.compid
     *
     * @param compid the value for md_department_member.compid
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public void setCompid(Integer compid) {
        this.compid = compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_department_member.deptid
     *
     * @return the value of md_department_member.deptid
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_department_member.deptid
     *
     * @param deptid the value for md_department_member.deptid
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_department_member.memberid
     *
     * @return the value of md_department_member.memberid
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_department_member.memberid
     *
     * @param memberid the value for md_department_member.memberid
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_department_member.deptrole
     *
     * @return the value of md_department_member.deptrole
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public Integer getDeptrole() {
        return deptrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_department_member.deptrole
     *
     * @param deptrole the value for md_department_member.deptrole
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public void setDeptrole(Integer deptrole) {
        this.deptrole = deptrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_department_member.createby
     *
     * @return the value of md_department_member.createby
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_department_member.createby
     *
     * @param createby the value for md_department_member.createby
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_department_member.createdate
     *
     * @return the value of md_department_member.createdate
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_department_member.createdate
     *
     * @param createdate the value for md_department_member.createdate
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_department_member.updateby
     *
     * @return the value of md_department_member.updateby
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_department_member.updateby
     *
     * @param updateby the value for md_department_member.updateby
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_department_member.updatedate
     *
     * @return the value of md_department_member.updatedate
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_department_member.updatedate
     *
     * @param updatedate the value for md_department_member.updatedate
     *
     * @mbggenerated Tue Nov 14 09:59:23 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
    @Override
	public String toString() {
		 return ReflectionToStringBuilder.toString(this); 
	}
}