package com.xiben.pm.md.pojo;

import java.util.Date;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class MdEmployeeEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.userid
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.username
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.nickname
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.dispname
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private String dispname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.truename
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.isshownickname
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private Integer isshownickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.email
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.phone
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.version
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.logourl
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private String logourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.authstatus
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private Integer authstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.status
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.superioruserid
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private Integer superioruserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.sex
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.createby
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.createdate
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.updateby
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_employee.updatedate
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.userid
     *
     * @return the value of md_employee.userid
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.userid
     *
     * @param userid the value for md_employee.userid
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.username
     *
     * @return the value of md_employee.username
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.username
     *
     * @param username the value for md_employee.username
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.nickname
     *
     * @return the value of md_employee.nickname
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.nickname
     *
     * @param nickname the value for md_employee.nickname
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.dispname
     *
     * @return the value of md_employee.dispname
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public String getDispname() {
        return dispname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.dispname
     *
     * @param dispname the value for md_employee.dispname
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setDispname(String dispname) {
        this.dispname = dispname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.truename
     *
     * @return the value of md_employee.truename
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.truename
     *
     * @param truename the value for md_employee.truename
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.isshownickname
     *
     * @return the value of md_employee.isshownickname
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public Integer getIsshownickname() {
        return isshownickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.isshownickname
     *
     * @param isshownickname the value for md_employee.isshownickname
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setIsshownickname(Integer isshownickname) {
        this.isshownickname = isshownickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.email
     *
     * @return the value of md_employee.email
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.email
     *
     * @param email the value for md_employee.email
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.phone
     *
     * @return the value of md_employee.phone
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.phone
     *
     * @param phone the value for md_employee.phone
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.version
     *
     * @return the value of md_employee.version
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.version
     *
     * @param version the value for md_employee.version
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.logourl
     *
     * @return the value of md_employee.logourl
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public String getLogourl() {
        return logourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.logourl
     *
     * @param logourl the value for md_employee.logourl
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setLogourl(String logourl) {
        this.logourl = logourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.authstatus
     *
     * @return the value of md_employee.authstatus
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public Integer getAuthstatus() {
        return authstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.authstatus
     *
     * @param authstatus the value for md_employee.authstatus
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setAuthstatus(Integer authstatus) {
        this.authstatus = authstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.status
     *
     * @return the value of md_employee.status
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.status
     *
     * @param status the value for md_employee.status
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.superioruserid
     *
     * @return the value of md_employee.superioruserid
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public Integer getSuperioruserid() {
        return superioruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.superioruserid
     *
     * @param superioruserid the value for md_employee.superioruserid
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setSuperioruserid(Integer superioruserid) {
        this.superioruserid = superioruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.sex
     *
     * @return the value of md_employee.sex
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.sex
     *
     * @param sex the value for md_employee.sex
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.createby
     *
     * @return the value of md_employee.createby
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.createby
     *
     * @param createby the value for md_employee.createby
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.createdate
     *
     * @return the value of md_employee.createdate
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.createdate
     *
     * @param createdate the value for md_employee.createdate
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.updateby
     *
     * @return the value of md_employee.updateby
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.updateby
     *
     * @param updateby the value for md_employee.updateby
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_employee.updatedate
     *
     * @return the value of md_employee.updatedate
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_employee.updatedate
     *
     * @param updatedate the value for md_employee.updatedate
     *
     * @mbggenerated Mon Oct 30 11:22:31 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
    @Override
	public String toString() {
		 return ReflectionToStringBuilder.toString(this); 
	}
}