package com.xiben.pm.md.pojo;

import java.util.Date;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class MdNotice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_notice.noticeid
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    private Integer noticeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_notice.msgcontent
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    private String msgcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_notice.biztype
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    private Integer biztype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_notice.bizid
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    private Integer bizid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_notice.senduserid
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    private Integer senduserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_notice.receiveuserid
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    private Integer receiveuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_notice.readflag
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    private Integer readflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_notice.sendflag
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    private Integer sendflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_notice.createby
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_notice.createdate
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_notice.updateby
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_notice.updatedate
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_notice.noticeid
     *
     * @return the value of md_notice.noticeid
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public Integer getNoticeid() {
        return noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_notice.noticeid
     *
     * @param noticeid the value for md_notice.noticeid
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public void setNoticeid(Integer noticeid) {
        this.noticeid = noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_notice.msgcontent
     *
     * @return the value of md_notice.msgcontent
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public String getMsgcontent() {
        return msgcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_notice.msgcontent
     *
     * @param msgcontent the value for md_notice.msgcontent
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public void setMsgcontent(String msgcontent) {
        this.msgcontent = msgcontent == null ? null : msgcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_notice.biztype
     *
     * @return the value of md_notice.biztype
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public Integer getBiztype() {
        return biztype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_notice.biztype
     *
     * @param biztype the value for md_notice.biztype
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public void setBiztype(Integer biztype) {
        this.biztype = biztype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_notice.bizid
     *
     * @return the value of md_notice.bizid
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public Integer getBizid() {
        return bizid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_notice.bizid
     *
     * @param bizid the value for md_notice.bizid
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public void setBizid(Integer bizid) {
        this.bizid = bizid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_notice.senduserid
     *
     * @return the value of md_notice.senduserid
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public Integer getSenduserid() {
        return senduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_notice.senduserid
     *
     * @param senduserid the value for md_notice.senduserid
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public void setSenduserid(Integer senduserid) {
        this.senduserid = senduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_notice.receiveuserid
     *
     * @return the value of md_notice.receiveuserid
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public Integer getReceiveuserid() {
        return receiveuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_notice.receiveuserid
     *
     * @param receiveuserid the value for md_notice.receiveuserid
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public void setReceiveuserid(Integer receiveuserid) {
        this.receiveuserid = receiveuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_notice.readflag
     *
     * @return the value of md_notice.readflag
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public Integer getReadflag() {
        return readflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_notice.readflag
     *
     * @param readflag the value for md_notice.readflag
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public void setReadflag(Integer readflag) {
        this.readflag = readflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_notice.sendflag
     *
     * @return the value of md_notice.sendflag
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public Integer getSendflag() {
        return sendflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_notice.sendflag
     *
     * @param sendflag the value for md_notice.sendflag
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public void setSendflag(Integer sendflag) {
        this.sendflag = sendflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_notice.createby
     *
     * @return the value of md_notice.createby
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_notice.createby
     *
     * @param createby the value for md_notice.createby
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_notice.createdate
     *
     * @return the value of md_notice.createdate
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_notice.createdate
     *
     * @param createdate the value for md_notice.createdate
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_notice.updateby
     *
     * @return the value of md_notice.updateby
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_notice.updateby
     *
     * @param updateby the value for md_notice.updateby
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_notice.updatedate
     *
     * @return the value of md_notice.updatedate
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_notice.updatedate
     *
     * @param updatedate the value for md_notice.updatedate
     *
     * @mbggenerated Tue Nov 21 13:51:33 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
    
    @Override
	public String toString() {
		 return ReflectionToStringBuilder.toString(this); 
	}
}