package com.xiben.pm.ar.mapper;

import com.xiben.pm.ar.pojo.ArArchive;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ArArchiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ar_archive
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    int deleteByPrimaryKey(Integer archiveid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ar_archive
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    int insert(ArArchive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ar_archive
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    int insertSelective(ArArchive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ar_archive
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    ArArchive selectByPrimaryKey(Integer archiveid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ar_archive
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    int updateByPrimaryKeySelective(ArArchive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ar_archive
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    int updateByPrimaryKey(ArArchive record);

    List<ArArchive> queryAllWithKeywords(@Param("keywords") String keywords);

}