package com.xiben.pm.ar.mapper;

import com.xiben.pm.ar.pojo.ArArchiveReadrecord;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ArArchiveReadrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ar_archive_readrecord
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ar_archive_readrecord
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    int insert(ArArchiveReadrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ar_archive_readrecord
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    int insertSelective(ArArchiveReadrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ar_archive_readrecord
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    ArArchiveReadrecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ar_archive_readrecord
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    int updateByPrimaryKeySelective(ArArchiveReadrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ar_archive_readrecord
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    int updateByPrimaryKey(ArArchiveReadrecord record);

    @Select("SELECT * FROM ar_archive_readrecord WHERE archiveid=#{archiveid,jdbcType=INTEGER} AND appid=#{appid,jdbcType=INTEGER}")
    List<ArArchiveReadrecord> queryByAppid(@Param("appid") Integer appid,@Param("archiveid") Integer archiveid);

}