package com.xiben.pm.tk.mapper;

import com.xiben.pm.tk.bean.DeptTaskScore;
import com.xiben.pm.tk.bean.IndexTaskBean;
import com.xiben.pm.tk.bean.TkTaskEx;
import com.xiben.pm.tk.pojo.TkTask;
import com.xiben.pm.tk.pojo.TkTaskExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TkTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_task
     *
     * @mbggenerated Fri Nov 17 09:34:34 CST 2017
     */
    int countByExample(TkTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_task
     *
     * @mbggenerated Fri Nov 17 09:34:34 CST 2017
     */
    int deleteByExample(TkTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_task
     *
     * @mbggenerated Fri Nov 17 09:34:34 CST 2017
     */
    int deleteByPrimaryKey(Integer taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_task
     *
     * @mbggenerated Fri Nov 17 09:34:34 CST 2017
     */
    int insert(TkTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_task
     *
     * @mbggenerated Fri Nov 17 09:34:34 CST 2017
     */
    int insertSelective(TkTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_task
     *
     * @mbggenerated Fri Nov 17 09:34:34 CST 2017
     */
    List<TkTask> selectByExample(TkTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_task
     *
     * @mbggenerated Fri Nov 17 09:34:34 CST 2017
     */
    TkTask selectByPrimaryKey(Integer taskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_task
     *
     * @mbggenerated Fri Nov 17 09:34:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") TkTask record, @Param("example") TkTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_task
     *
     * @mbggenerated Fri Nov 17 09:34:34 CST 2017
     */
    int updateByExample(@Param("record") TkTask record, @Param("example") TkTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_task
     *
     * @mbggenerated Fri Nov 17 09:34:34 CST 2017
     */
    int updateByPrimaryKeySelective(TkTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_task
     *
     * @mbggenerated Fri Nov 17 09:34:34 CST 2017
     */
    int updateByPrimaryKey(TkTask record);

    
	DeptTaskScore getDeptTaskScore( @Param("deptid")Integer deptid, @Param("publish")Date publishdt);

	Integer getTaskNum( @Param("deptid")Integer deptid,  @Param("dutyid")Integer dutyid);

	@Select("select * from tk_task a where a.deptid=#{deptid,jdbcType=INTEGER} and a.`status` <> 3")
	List<TkTask> getNofinished(@Param("deptid")Integer deptid);

	List<TkTaskEx> getByDutyid(@Param("userid")Integer userid ,@Param("dutyid")Integer dutyid,@Param("companyid")Integer companyid,@Param("deptid")Integer detpid);

   @Update("update tk_task  set `status`=#{status,jdbcType=INTEGER},createby=#{userid,jdbcType=INTEGER},createdate=NOW() where `status`=1 and taskid=#{taskid,jdbcType=INTEGER}")
	int updateByStatus(@Param("userid")Integer userid,@Param("status")Integer status, @Param("taskid")Integer taskid);
   
   @Update("update tk_task  set score=#{score,jdbcType=INTEGER} , `status`=#{status,jdbcType=INTEGER},createby=#{userid,jdbcType=INTEGER},createdate=NOW() where `status` in(1,2) and taskid=#{taskid,jdbcType=INTEGER}")
  	int updateScoreByStatus(@Param("score")Integer score,@Param("userid")Integer userid,@Param("status")Integer status, @Param("taskid")Integer taskid);

  List<IndexTaskBean> queryIndex(@Param("userid")Integer userid);
     
}