package com.xiben.pm.tk.mapper;

import com.xiben.pm.tk.pojo.TkTasknode;
import com.xiben.pm.tk.pojo.TkTasknodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface TkTasknodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_tasknode
     *
     * @mbggenerated Tue Nov 21 09:04:33 CST 2017
     */
    int countByExample(TkTasknodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_tasknode
     *
     * @mbggenerated Tue Nov 21 09:04:33 CST 2017
     */
    int deleteByExample(TkTasknodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_tasknode
     *
     * @mbggenerated Tue Nov 21 09:04:33 CST 2017
     */
    int deleteByPrimaryKey(Integer nodeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_tasknode
     *
     * @mbggenerated Tue Nov 21 09:04:33 CST 2017
     */
    int insert(TkTasknode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_tasknode
     *
     * @mbggenerated Tue Nov 21 09:04:33 CST 2017
     */
    int insertSelective(TkTasknode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_tasknode
     *
     * @mbggenerated Tue Nov 21 09:04:33 CST 2017
     */
    List<TkTasknode> selectByExample(TkTasknodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_tasknode
     *
     * @mbggenerated Tue Nov 21 09:04:33 CST 2017
     */
    TkTasknode selectByPrimaryKey(Integer nodeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_tasknode
     *
     * @mbggenerated Tue Nov 21 09:04:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") TkTasknode record, @Param("example") TkTasknodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_tasknode
     *
     * @mbggenerated Tue Nov 21 09:04:33 CST 2017
     */
    int updateByExample(@Param("record") TkTasknode record, @Param("example") TkTasknodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_tasknode
     *
     * @mbggenerated Tue Nov 21 09:04:33 CST 2017
     */
    int updateByPrimaryKeySelective(TkTasknode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_tasknode
     *
     * @mbggenerated Tue Nov 21 09:04:33 CST 2017
     */
    int updateByPrimaryKey(TkTasknode record);
    @Select("select * from tk_tasknode n where n.taskid=#{taskid,jdbcType=INTEGER}")
	List<TkTasknode> queryByTaskId(@Param("taskid")Integer taskid);
}