package com.xiben.pm.wf.pojo;

import java.util.Date;

public class WfInstanceNodeApproveUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.id
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.compid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer compid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.userid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.insid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer insid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.insnodeid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer insnodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.inspartid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer inspartid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.templateid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer templateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.templatenodeid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer templatenodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.deptid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.remark
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.status
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.createby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node_approve_user.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.id
     *
     * @return the value of wf_instance_node_approve_user.id
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.id
     *
     * @param id the value for wf_instance_node_approve_user.id
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.compid
     *
     * @return the value of wf_instance_node_approve_user.compid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getCompid() {
        return compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.compid
     *
     * @param compid the value for wf_instance_node_approve_user.compid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setCompid(Integer compid) {
        this.compid = compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.userid
     *
     * @return the value of wf_instance_node_approve_user.userid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.userid
     *
     * @param userid the value for wf_instance_node_approve_user.userid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.insid
     *
     * @return the value of wf_instance_node_approve_user.insid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getInsid() {
        return insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.insid
     *
     * @param insid the value for wf_instance_node_approve_user.insid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setInsid(Integer insid) {
        this.insid = insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.insnodeid
     *
     * @return the value of wf_instance_node_approve_user.insnodeid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getInsnodeid() {
        return insnodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.insnodeid
     *
     * @param insnodeid the value for wf_instance_node_approve_user.insnodeid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setInsnodeid(Integer insnodeid) {
        this.insnodeid = insnodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.inspartid
     *
     * @return the value of wf_instance_node_approve_user.inspartid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getInspartid() {
        return inspartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.inspartid
     *
     * @param inspartid the value for wf_instance_node_approve_user.inspartid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setInspartid(Integer inspartid) {
        this.inspartid = inspartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.templateid
     *
     * @return the value of wf_instance_node_approve_user.templateid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.templateid
     *
     * @param templateid the value for wf_instance_node_approve_user.templateid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.templatenodeid
     *
     * @return the value of wf_instance_node_approve_user.templatenodeid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getTemplatenodeid() {
        return templatenodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.templatenodeid
     *
     * @param templatenodeid the value for wf_instance_node_approve_user.templatenodeid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setTemplatenodeid(Integer templatenodeid) {
        this.templatenodeid = templatenodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.deptid
     *
     * @return the value of wf_instance_node_approve_user.deptid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.deptid
     *
     * @param deptid the value for wf_instance_node_approve_user.deptid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.remark
     *
     * @return the value of wf_instance_node_approve_user.remark
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.remark
     *
     * @param remark the value for wf_instance_node_approve_user.remark
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.status
     *
     * @return the value of wf_instance_node_approve_user.status
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.status
     *
     * @param status the value for wf_instance_node_approve_user.status
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.createby
     *
     * @return the value of wf_instance_node_approve_user.createby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.createby
     *
     * @param createby the value for wf_instance_node_approve_user.createby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.createdate
     *
     * @return the value of wf_instance_node_approve_user.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.createdate
     *
     * @param createdate the value for wf_instance_node_approve_user.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.updateby
     *
     * @return the value of wf_instance_node_approve_user.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.updateby
     *
     * @param updateby the value for wf_instance_node_approve_user.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node_approve_user.updatedate
     *
     * @return the value of wf_instance_node_approve_user.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node_approve_user.updatedate
     *
     * @param updatedate the value for wf_instance_node_approve_user.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}