package com.xiben.pm.wf.pojo;

import java.util.Date;

public class WfInstanceNode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node.insnodeid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    private Integer insnodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node.insid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    private Integer insid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node.templatenodeid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    private Integer templatenodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node.compid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    private Integer compid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node.templateid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    private Integer templateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node.nodename
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    private String nodename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node.approvetype
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    private Integer approvetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node.notetype
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    private Integer notetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node.status
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node.createby
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node.createdate
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node.updateby
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_instance_node.updatedate
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node.insnodeid
     *
     * @return the value of wf_instance_node.insnodeid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public Integer getInsnodeid() {
        return insnodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node.insnodeid
     *
     * @param insnodeid the value for wf_instance_node.insnodeid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public void setInsnodeid(Integer insnodeid) {
        this.insnodeid = insnodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node.insid
     *
     * @return the value of wf_instance_node.insid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public Integer getInsid() {
        return insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node.insid
     *
     * @param insid the value for wf_instance_node.insid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public void setInsid(Integer insid) {
        this.insid = insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node.templatenodeid
     *
     * @return the value of wf_instance_node.templatenodeid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public Integer getTemplatenodeid() {
        return templatenodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node.templatenodeid
     *
     * @param templatenodeid the value for wf_instance_node.templatenodeid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public void setTemplatenodeid(Integer templatenodeid) {
        this.templatenodeid = templatenodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node.compid
     *
     * @return the value of wf_instance_node.compid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public Integer getCompid() {
        return compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node.compid
     *
     * @param compid the value for wf_instance_node.compid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public void setCompid(Integer compid) {
        this.compid = compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node.templateid
     *
     * @return the value of wf_instance_node.templateid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node.templateid
     *
     * @param templateid the value for wf_instance_node.templateid
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node.nodename
     *
     * @return the value of wf_instance_node.nodename
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public String getNodename() {
        return nodename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node.nodename
     *
     * @param nodename the value for wf_instance_node.nodename
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public void setNodename(String nodename) {
        this.nodename = nodename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node.approvetype
     *
     * @return the value of wf_instance_node.approvetype
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public Integer getApprovetype() {
        return approvetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node.approvetype
     *
     * @param approvetype the value for wf_instance_node.approvetype
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public void setApprovetype(Integer approvetype) {
        this.approvetype = approvetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node.notetype
     *
     * @return the value of wf_instance_node.notetype
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public Integer getNotetype() {
        return notetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node.notetype
     *
     * @param notetype the value for wf_instance_node.notetype
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public void setNotetype(Integer notetype) {
        this.notetype = notetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node.status
     *
     * @return the value of wf_instance_node.status
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node.status
     *
     * @param status the value for wf_instance_node.status
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node.createby
     *
     * @return the value of wf_instance_node.createby
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node.createby
     *
     * @param createby the value for wf_instance_node.createby
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node.createdate
     *
     * @return the value of wf_instance_node.createdate
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node.createdate
     *
     * @param createdate the value for wf_instance_node.createdate
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node.updateby
     *
     * @return the value of wf_instance_node.updateby
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node.updateby
     *
     * @param updateby the value for wf_instance_node.updateby
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_instance_node.updatedate
     *
     * @return the value of wf_instance_node.updatedate
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_instance_node.updatedate
     *
     * @param updatedate the value for wf_instance_node.updatedate
     *
     * @mbggenerated Fri Nov 17 15:43:58 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}