package com.xiben.pm.wf.pojo;

import java.util.Date;

public class WfTemplateNodeApprovepart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node_approvepart.templatepartid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer templatepartid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node_approvepart.compid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer compid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node_approvepart.templateid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer templateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node_approvepart.templatenodeid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer templatenodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node_approvepart.deptid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node_approvepart.approvetype
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer approvetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node_approvepart.createby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node_approvepart.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node_approvepart.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node_approvepart.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node_approvepart.templatepartid
     *
     * @return the value of wf_template_node_approvepart.templatepartid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getTemplatepartid() {
        return templatepartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node_approvepart.templatepartid
     *
     * @param templatepartid the value for wf_template_node_approvepart.templatepartid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setTemplatepartid(Integer templatepartid) {
        this.templatepartid = templatepartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node_approvepart.compid
     *
     * @return the value of wf_template_node_approvepart.compid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getCompid() {
        return compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node_approvepart.compid
     *
     * @param compid the value for wf_template_node_approvepart.compid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setCompid(Integer compid) {
        this.compid = compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node_approvepart.templateid
     *
     * @return the value of wf_template_node_approvepart.templateid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node_approvepart.templateid
     *
     * @param templateid the value for wf_template_node_approvepart.templateid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node_approvepart.templatenodeid
     *
     * @return the value of wf_template_node_approvepart.templatenodeid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getTemplatenodeid() {
        return templatenodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node_approvepart.templatenodeid
     *
     * @param templatenodeid the value for wf_template_node_approvepart.templatenodeid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setTemplatenodeid(Integer templatenodeid) {
        this.templatenodeid = templatenodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node_approvepart.deptid
     *
     * @return the value of wf_template_node_approvepart.deptid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node_approvepart.deptid
     *
     * @param deptid the value for wf_template_node_approvepart.deptid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node_approvepart.approvetype
     *
     * @return the value of wf_template_node_approvepart.approvetype
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getApprovetype() {
        return approvetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node_approvepart.approvetype
     *
     * @param approvetype the value for wf_template_node_approvepart.approvetype
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setApprovetype(Integer approvetype) {
        this.approvetype = approvetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node_approvepart.createby
     *
     * @return the value of wf_template_node_approvepart.createby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node_approvepart.createby
     *
     * @param createby the value for wf_template_node_approvepart.createby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node_approvepart.createdate
     *
     * @return the value of wf_template_node_approvepart.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node_approvepart.createdate
     *
     * @param createdate the value for wf_template_node_approvepart.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node_approvepart.updateby
     *
     * @return the value of wf_template_node_approvepart.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node_approvepart.updateby
     *
     * @param updateby the value for wf_template_node_approvepart.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node_approvepart.updatedate
     *
     * @return the value of wf_template_node_approvepart.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node_approvepart.updatedate
     *
     * @param updatedate the value for wf_template_node_approvepart.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}