package com.xiben.pm.wf.pojo;

import java.util.Date;

public class WfTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template.templateid
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    private Integer templateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template.compid
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    private Integer compid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template.templatename
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    private String templatename;
    
    private String templateremark;
    
    
    

    public String getTemplateremark() {
		return templateremark;
	}

	public void setTemplateremark(String templateremark) {
		this.templateremark = templateremark;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template.type
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template.deptdutyid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017

     */
    private Integer createtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template.status
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template.createby
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template.createdate
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template.updateby
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template.updatedate
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template.templateid
     *
     * @return the value of wf_template.templateid
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template.templateid
     *
     * @param templateid the value for wf_template.templateid
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template.compid
     *
     * @return the value of wf_template.compid
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public Integer getCompid() {
        return compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template.compid
     *
     * @param compid the value for wf_template.compid
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public void setCompid(Integer compid) {
        this.compid = compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template.templatename
     *
     * @return the value of wf_template.templatename
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public String getTemplatename() {
        return templatename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template.templatename
     *
     * @param templatename the value for wf_template.templatename
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public void setTemplatename(String templatename) {
        this.templatename = templatename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template.type
     *
     * @return the value of wf_template.type
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template.type
     *
     * @param type the value for wf_template.type
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template.createtype
     *
     * @return the value of wf_template.createtype
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public Integer getCreatetype() {
        return createtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template.createtype
     *
     * @param createtype the value for wf_template.createtype
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public void setCreatetype(Integer createtype) {
        this.createtype = createtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template.status
     *
     * @return the value of wf_template.status
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template.status
     *
     * @param status the value for wf_template.status
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template.createby
     *
     * @return the value of wf_template.createby
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template.createby
     *
     * @param createby the value for wf_template.createby
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template.createdate
     *
     * @return the value of wf_template.createdate
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template.createdate
     *
     * @param createdate the value for wf_template.createdate
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template.updateby
     *
     * @return the value of wf_template.updateby
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template.updateby
     *
     * @param updateby the value for wf_template.updateby
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template.updatedate
     *
     * @return the value of wf_template.updatedate
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template.updatedate
     *
     * @param updatedate the value for wf_template.updatedate
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}