package com.xiben.pm.wf.pojo;

import java.util.Date;

public class WfTemplateNode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node.templatenodeid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer templatenodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node.compid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer compid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node.templateid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer templateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node.nodename
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private String nodename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node.approvetype
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer approvetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node.notetype
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer notetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node.createtype
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer createtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node.rank
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node.createby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_template_node.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node.templatenodeid
     *
     * @return the value of wf_template_node.templatenodeid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getTemplatenodeid() {
        return templatenodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node.templatenodeid
     *
     * @param templatenodeid the value for wf_template_node.templatenodeid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setTemplatenodeid(Integer templatenodeid) {
        this.templatenodeid = templatenodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node.compid
     *
     * @return the value of wf_template_node.compid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getCompid() {
        return compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node.compid
     *
     * @param compid the value for wf_template_node.compid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setCompid(Integer compid) {
        this.compid = compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node.templateid
     *
     * @return the value of wf_template_node.templateid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node.templateid
     *
     * @param templateid the value for wf_template_node.templateid
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node.nodename
     *
     * @return the value of wf_template_node.nodename
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public String getNodename() {
        return nodename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node.nodename
     *
     * @param nodename the value for wf_template_node.nodename
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setNodename(String nodename) {
        this.nodename = nodename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node.approvetype
     *
     * @return the value of wf_template_node.approvetype
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getApprovetype() {
        return approvetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node.approvetype
     *
     * @param approvetype the value for wf_template_node.approvetype
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setApprovetype(Integer approvetype) {
        this.approvetype = approvetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node.notetype
     *
     * @return the value of wf_template_node.notetype
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getNotetype() {
        return notetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node.notetype
     *
     * @param notetype the value for wf_template_node.notetype
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setNotetype(Integer notetype) {
        this.notetype = notetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node.createtype
     *
     * @return the value of wf_template_node.createtype
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getCreatetype() {
        return createtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node.createtype
     *
     * @param createtype the value for wf_template_node.createtype
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setCreatetype(Integer createtype) {
        this.createtype = createtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node.rank
     *
     * @return the value of wf_template_node.rank
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node.rank
     *
     * @param rank the value for wf_template_node.rank
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node.createby
     *
     * @return the value of wf_template_node.createby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node.createby
     *
     * @param createby the value for wf_template_node.createby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node.createdate
     *
     * @return the value of wf_template_node.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node.createdate
     *
     * @param createdate the value for wf_template_node.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node.updateby
     *
     * @return the value of wf_template_node.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node.updateby
     *
     * @param updateby the value for wf_template_node.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_template_node.updatedate
     *
     * @return the value of wf_template_node.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_template_node.updatedate
     *
     * @param updatedate the value for wf_template_node.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}