package com.xiben.pm.wf.mapper;

import com.xiben.pm.wf.pojo.WfInstanceNode;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WfInstanceNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_instance_node
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    int deleteByPrimaryKey(Integer insnodeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_instance_node
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    int insert(WfInstanceNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_instance_node
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    int insertSelective(WfInstanceNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_instance_node
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    WfInstanceNode selectByPrimaryKey(Integer insnodeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_instance_node
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    int updateByPrimaryKeySelective(WfInstanceNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_instance_node
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    int updateByPrimaryKey(WfInstanceNode record);
    
    WfInstanceNode selectInsNoApproveStartNode(int insid);
    List<WfInstanceNode> queryBy(@Param("field") String field, @Param("val") String value);
    List<WfInstanceNode> queryBy1(@Param("field") String field,@Param("val") String value,
                                  @Param("field1") String field1,@Param("val1") String value1);
    List<WfInstanceNode> queryBy2(@Param("field") String field,@Param("val") String value,
                                  @Param("field1") String field1,@Param("val1") String value1,
                                  @Param("field2") String field2,@Param("val2") String value2);
}