package com.xiben.pm.wf.mapper;

import com.xiben.pm.wf.pojo.WfTemplate;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface WfTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_template
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    int deleteByPrimaryKey(Integer templateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_template
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    int insert(WfTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_template
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    int insertSelective(WfTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_template
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    WfTemplate selectByPrimaryKey(Integer templateid);

    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_template
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    int updateByPrimaryKeySelective(WfTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_template
     *
     * @mbggenerated Wed Nov 15 15:27:40 CST 2017
     */
    int updateByPrimaryKey(WfTemplate record);


    List<WfTemplate> queryListByCompid(@Param("compid") Integer compid,@Param("type") Integer type);

}