package com.xiben.pm.wf.mapper;

import com.xiben.pm.wf.pojo.WfTemplateNodeApprovepart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WfTemplateNodeApprovepartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_template_node_approvepart
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    int deleteByPrimaryKey(Integer templatepartid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_template_node_approvepart
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    int insert(WfTemplateNodeApprovepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_template_node_approvepart
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    int insertSelective(WfTemplateNodeApprovepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_template_node_approvepart
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    WfTemplateNodeApprovepart selectByPrimaryKey(Integer templatepartid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_template_node_approvepart
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    int updateByPrimaryKeySelective(WfTemplateNodeApprovepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_template_node_approvepart
     *
     * @mbggenerated Tue Nov 14 14:06:07 CST 2017
     */
    int updateByPrimaryKey(WfTemplateNodeApprovepart record);


    List<WfTemplateNodeApprovepart> queryAll();
    List<WfTemplateNodeApprovepart> queryBy(@Param("field") String filed,@Param("val") String val);
    void deleteAllWithTempId(Integer templateid);

    WfTemplateNodeApprovepart selectTemplateNodePartByNodeIdAndDeptid(java.util.Map<String,Integer> param);
    
    List<WfTemplateNodeApprovepart> selectTemplateNodePartListByNodeId(Integer templateNodeId);

    List<WfTemplateNodeApprovepart> queryByCTT(@Param("compid") Integer compid,@Param("templateid") Integer templateid, @Param("templatenodeid") Integer templatenodeid);
}