package com.xiben.pm.ar.pojo;

import java.util.Date;

public class ArArchiveSecretapproveuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_secretapproveuser.id
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_secretapproveuser.approveuserid
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    private Integer approveuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_secretapproveuser.archiveid
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    private Integer archiveid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_secretapproveuser.createby
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_secretapproveuser.createdate
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_secretapproveuser.updateby
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_secretapproveuser.updatedate
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_secretapproveuser.id
     *
     * @return the value of ar_archive_secretapproveuser.id
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_secretapproveuser.id
     *
     * @param id the value for ar_archive_secretapproveuser.id
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_secretapproveuser.approveuserid
     *
     * @return the value of ar_archive_secretapproveuser.approveuserid
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    public Integer getApproveuserid() {
        return approveuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_secretapproveuser.approveuserid
     *
     * @param approveuserid the value for ar_archive_secretapproveuser.approveuserid
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    public void setApproveuserid(Integer approveuserid) {
        this.approveuserid = approveuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_secretapproveuser.archiveid
     *
     * @return the value of ar_archive_secretapproveuser.archiveid
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    public Integer getArchiveid() {
        return archiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_secretapproveuser.archiveid
     *
     * @param archiveid the value for ar_archive_secretapproveuser.archiveid
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    public void setArchiveid(Integer archiveid) {
        this.archiveid = archiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_secretapproveuser.createby
     *
     * @return the value of ar_archive_secretapproveuser.createby
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_secretapproveuser.createby
     *
     * @param createby the value for ar_archive_secretapproveuser.createby
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_secretapproveuser.createdate
     *
     * @return the value of ar_archive_secretapproveuser.createdate
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_secretapproveuser.createdate
     *
     * @param createdate the value for ar_archive_secretapproveuser.createdate
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_secretapproveuser.updateby
     *
     * @return the value of ar_archive_secretapproveuser.updateby
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_secretapproveuser.updateby
     *
     * @param updateby the value for ar_archive_secretapproveuser.updateby
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_secretapproveuser.updatedate
     *
     * @return the value of ar_archive_secretapproveuser.updatedate
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_secretapproveuser.updatedate
     *
     * @param updatedate the value for ar_archive_secretapproveuser.updatedate
     *
     * @mbggenerated Tue Nov 21 13:26:49 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}