package com.xiben.pm.ar.pojo;

import java.util.Date;

public class ArArchiveSequence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_sequence.id
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_sequence.compid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Integer compid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_sequence.groupno
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private String groupno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_sequence.currentnumber
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Integer currentnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_sequence.createby
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_sequence.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_sequence.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_sequence.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_sequence.id
     *
     * @return the value of ar_archive_sequence.id
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_sequence.id
     *
     * @param id the value for ar_archive_sequence.id
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_sequence.compid
     *
     * @return the value of ar_archive_sequence.compid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Integer getCompid() {
        return compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_sequence.compid
     *
     * @param compid the value for ar_archive_sequence.compid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setCompid(Integer compid) {
        this.compid = compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_sequence.groupno
     *
     * @return the value of ar_archive_sequence.groupno
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public String getGroupno() {
        return groupno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_sequence.groupno
     *
     * @param groupno the value for ar_archive_sequence.groupno
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setGroupno(String groupno) {
        this.groupno = groupno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_sequence.currentnumber
     *
     * @return the value of ar_archive_sequence.currentnumber
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Integer getCurrentnumber() {
        return currentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_sequence.currentnumber
     *
     * @param currentnumber the value for ar_archive_sequence.currentnumber
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setCurrentnumber(Integer currentnumber) {
        this.currentnumber = currentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_sequence.createby
     *
     * @return the value of ar_archive_sequence.createby
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_sequence.createby
     *
     * @param createby the value for ar_archive_sequence.createby
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_sequence.createdate
     *
     * @return the value of ar_archive_sequence.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_sequence.createdate
     *
     * @param createdate the value for ar_archive_sequence.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_sequence.updateby
     *
     * @return the value of ar_archive_sequence.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_sequence.updateby
     *
     * @param updateby the value for ar_archive_sequence.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_sequence.updatedate
     *
     * @return the value of ar_archive_sequence.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_sequence.updatedate
     *
     * @param updatedate the value for ar_archive_sequence.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}