package com.xiben.pm.ar.pojo;

import java.util.Date;

public class ArArchiveReadrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_readrecord.id
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_readrecord.appid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Integer appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_readrecord.compid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Integer compid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_readrecord.archiveid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Integer archiveid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_readrecord.approvedate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Date approvedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_readrecord.approveuserid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Integer approveuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_readrecord.readdate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Date readdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_readrecord.readuserid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Integer readuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_readrecord.status
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_readrecord.createby
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_readrecord.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_readrecord.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ar_archive_readrecord.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_readrecord.id
     *
     * @return the value of ar_archive_readrecord.id
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_readrecord.id
     *
     * @param id the value for ar_archive_readrecord.id
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_readrecord.appid
     *
     * @return the value of ar_archive_readrecord.appid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_readrecord.appid
     *
     * @param appid the value for ar_archive_readrecord.appid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_readrecord.compid
     *
     * @return the value of ar_archive_readrecord.compid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Integer getCompid() {
        return compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_readrecord.compid
     *
     * @param compid the value for ar_archive_readrecord.compid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setCompid(Integer compid) {
        this.compid = compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_readrecord.archiveid
     *
     * @return the value of ar_archive_readrecord.archiveid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Integer getArchiveid() {
        return archiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_readrecord.archiveid
     *
     * @param archiveid the value for ar_archive_readrecord.archiveid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setArchiveid(Integer archiveid) {
        this.archiveid = archiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_readrecord.approvedate
     *
     * @return the value of ar_archive_readrecord.approvedate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Date getApprovedate() {
        return approvedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_readrecord.approvedate
     *
     * @param approvedate the value for ar_archive_readrecord.approvedate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setApprovedate(Date approvedate) {
        this.approvedate = approvedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_readrecord.approveuserid
     *
     * @return the value of ar_archive_readrecord.approveuserid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Integer getApproveuserid() {
        return approveuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_readrecord.approveuserid
     *
     * @param approveuserid the value for ar_archive_readrecord.approveuserid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setApproveuserid(Integer approveuserid) {
        this.approveuserid = approveuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_readrecord.readdate
     *
     * @return the value of ar_archive_readrecord.readdate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Date getReaddate() {
        return readdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_readrecord.readdate
     *
     * @param readdate the value for ar_archive_readrecord.readdate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setReaddate(Date readdate) {
        this.readdate = readdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_readrecord.readuserid
     *
     * @return the value of ar_archive_readrecord.readuserid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Integer getReaduserid() {
        return readuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_readrecord.readuserid
     *
     * @param readuserid the value for ar_archive_readrecord.readuserid
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setReaduserid(Integer readuserid) {
        this.readuserid = readuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_readrecord.status
     *
     * @return the value of ar_archive_readrecord.status
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_readrecord.status
     *
     * @param status the value for ar_archive_readrecord.status
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_readrecord.createby
     *
     * @return the value of ar_archive_readrecord.createby
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_readrecord.createby
     *
     * @param createby the value for ar_archive_readrecord.createby
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_readrecord.createdate
     *
     * @return the value of ar_archive_readrecord.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_readrecord.createdate
     *
     * @param createdate the value for ar_archive_readrecord.createdate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_readrecord.updateby
     *
     * @return the value of ar_archive_readrecord.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_readrecord.updateby
     *
     * @param updateby the value for ar_archive_readrecord.updateby
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ar_archive_readrecord.updatedate
     *
     * @return the value of ar_archive_readrecord.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ar_archive_readrecord.updatedate
     *
     * @param updatedate the value for ar_archive_readrecord.updatedate
     *
     * @mbggenerated Tue Nov 14 14:06:28 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}