package com.xiben.pm.tk.pojo;

import java.math.BigDecimal;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class TkTaskMonthScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_task_monthscore.id
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_task_monthscore.compid
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    private Integer compid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_task_monthscore.deptid
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_task_monthscore.year
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_task_monthscore.month
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_task_monthscore.taskscore
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    private BigDecimal taskscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_task_monthscore.status
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_task_monthscore.id
     *
     * @return the value of tk_task_monthscore.id
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_task_monthscore.id
     *
     * @param id the value for tk_task_monthscore.id
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_task_monthscore.compid
     *
     * @return the value of tk_task_monthscore.compid
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    public Integer getCompid() {
        return compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_task_monthscore.compid
     *
     * @param compid the value for tk_task_monthscore.compid
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    public void setCompid(Integer compid) {
        this.compid = compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_task_monthscore.deptid
     *
     * @return the value of tk_task_monthscore.deptid
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_task_monthscore.deptid
     *
     * @param deptid the value for tk_task_monthscore.deptid
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_task_monthscore.year
     *
     * @return the value of tk_task_monthscore.year
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_task_monthscore.year
     *
     * @param year the value for tk_task_monthscore.year
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_task_monthscore.month
     *
     * @return the value of tk_task_monthscore.month
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_task_monthscore.month
     *
     * @param month the value for tk_task_monthscore.month
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_task_monthscore.taskscore
     *
     * @return the value of tk_task_monthscore.taskscore
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    public BigDecimal getTaskscore() {
        return taskscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_task_monthscore.taskscore
     *
     * @param taskscore the value for tk_task_monthscore.taskscore
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    public void setTaskscore(BigDecimal taskscore) {
        this.taskscore = taskscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_task_monthscore.status
     *
     * @return the value of tk_task_monthscore.status
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_task_monthscore.status
     *
     * @param status the value for tk_task_monthscore.status
     *
     * @mbggenerated Thu Nov 23 08:59:43 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
    @Override
  	public String toString() {
  		 return ReflectionToStringBuilder.toString(this); 
  	}
}