package com.xiben.sso.site.bean;

import java.io.Serializable;
import java.util.Date;

public class OauthCode implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_code.userid
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_code.createtime
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_code.code
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_code.clientid
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    private String clientid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_code.userid
     *
     * @return the value of oauth_code.userid
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_code.userid
     *
     * @param userid the value for oauth_code.userid
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_code.createtime
     *
     * @return the value of oauth_code.createtime
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_code.createtime
     *
     * @param createtime the value for oauth_code.createtime
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_code.code
     *
     * @return the value of oauth_code.code
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_code.code
     *
     * @param code the value for oauth_code.code
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_code.clientid
     *
     * @return the value of oauth_code.clientid
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_code.clientid
     *
     * @param clientid the value for oauth_code.clientid
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public void setClientid(String clientid) {
        this.clientid = clientid == null ? null : clientid.trim();
    }
}