package com.xiben.sso.site.bean;

import java.io.Serializable;
import java.util.Date;

public class OauthClientDetails implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client_details.client_id
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client_details.client_secret
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    private String clientSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client_details.authorized_grant_types
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    private String authorizedGrantTypes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client_details.create_time
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client_details.ispublic
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    private Integer ispublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client_details.description
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client_details.client_host_url
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    private String clientHostUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client_details.client_logout_url
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    private String clientLogoutUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client_details.status
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_client_details.client_type
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    private Integer clientType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client_details.client_id
     *
     * @return the value of oauth_client_details.client_id
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client_details.client_id
     *
     * @param clientId the value for oauth_client_details.client_id
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client_details.client_secret
     *
     * @return the value of oauth_client_details.client_secret
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public String getClientSecret() {
        return clientSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client_details.client_secret
     *
     * @param clientSecret the value for oauth_client_details.client_secret
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret == null ? null : clientSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client_details.authorized_grant_types
     *
     * @return the value of oauth_client_details.authorized_grant_types
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public String getAuthorizedGrantTypes() {
        return authorizedGrantTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client_details.authorized_grant_types
     *
     * @param authorizedGrantTypes the value for oauth_client_details.authorized_grant_types
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public void setAuthorizedGrantTypes(String authorizedGrantTypes) {
        this.authorizedGrantTypes = authorizedGrantTypes == null ? null : authorizedGrantTypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client_details.create_time
     *
     * @return the value of oauth_client_details.create_time
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client_details.create_time
     *
     * @param createTime the value for oauth_client_details.create_time
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client_details.ispublic
     *
     * @return the value of oauth_client_details.ispublic
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public Integer getIspublic() {
        return ispublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client_details.ispublic
     *
     * @param ispublic the value for oauth_client_details.ispublic
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public void setIspublic(Integer ispublic) {
        this.ispublic = ispublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client_details.description
     *
     * @return the value of oauth_client_details.description
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client_details.description
     *
     * @param description the value for oauth_client_details.description
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client_details.client_host_url
     *
     * @return the value of oauth_client_details.client_host_url
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public String getClientHostUrl() {
        return clientHostUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client_details.client_host_url
     *
     * @param clientHostUrl the value for oauth_client_details.client_host_url
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public void setClientHostUrl(String clientHostUrl) {
        this.clientHostUrl = clientHostUrl == null ? null : clientHostUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client_details.client_logout_url
     *
     * @return the value of oauth_client_details.client_logout_url
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public String getClientLogoutUrl() {
        return clientLogoutUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client_details.client_logout_url
     *
     * @param clientLogoutUrl the value for oauth_client_details.client_logout_url
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public void setClientLogoutUrl(String clientLogoutUrl) {
        this.clientLogoutUrl = clientLogoutUrl == null ? null : clientLogoutUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client_details.status
     *
     * @return the value of oauth_client_details.status
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client_details.status
     *
     * @param status the value for oauth_client_details.status
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_client_details.client_type
     *
     * @return the value of oauth_client_details.client_type
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public Integer getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_client_details.client_type
     *
     * @param clientType the value for oauth_client_details.client_type
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    public void setClientType(Integer clientType) {
        this.clientType = clientType;
    }
}