package com.xiben.sso.site.bean;

import java.io.Serializable;
import java.util.Date;

public class User_ implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.id
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.guid
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.username
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.password
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.nickname
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.phone
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.email
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.logourl
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private String logourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.last_login_time
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.create_time
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.version
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.smscode
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private String smscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.archived
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Boolean archived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.default_user
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Boolean defaultUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.createby
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.createdate
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.updateby
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.updatedate
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.dispname
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private String dispname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.truename
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.isshownickname
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Integer isshownickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.sex
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.superioruserid
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Integer superioruserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.securitypass
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private String securitypass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.securitylevel
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Integer securitylevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.authstatus
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Integer authstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.status
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.id
     *
     * @return the value of user_.id
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.id
     *
     * @param id the value for user_.id
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.guid
     *
     * @return the value of user_.guid
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.guid
     *
     * @param guid the value for user_.guid
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.username
     *
     * @return the value of user_.username
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.username
     *
     * @param username the value for user_.username
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.password
     *
     * @return the value of user_.password
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.password
     *
     * @param password the value for user_.password
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.nickname
     *
     * @return the value of user_.nickname
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.nickname
     *
     * @param nickname the value for user_.nickname
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.phone
     *
     * @return the value of user_.phone
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.phone
     *
     * @param phone the value for user_.phone
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.email
     *
     * @return the value of user_.email
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.email
     *
     * @param email the value for user_.email
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.logourl
     *
     * @return the value of user_.logourl
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public String getLogourl() {
        return logourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.logourl
     *
     * @param logourl the value for user_.logourl
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setLogourl(String logourl) {
        this.logourl = logourl == null ? null : logourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.last_login_time
     *
     * @return the value of user_.last_login_time
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.last_login_time
     *
     * @param lastLoginTime the value for user_.last_login_time
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.create_time
     *
     * @return the value of user_.create_time
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.create_time
     *
     * @param createTime the value for user_.create_time
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.version
     *
     * @return the value of user_.version
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.version
     *
     * @param version the value for user_.version
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.smscode
     *
     * @return the value of user_.smscode
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public String getSmscode() {
        return smscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.smscode
     *
     * @param smscode the value for user_.smscode
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setSmscode(String smscode) {
        this.smscode = smscode == null ? null : smscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.archived
     *
     * @return the value of user_.archived
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Boolean getArchived() {
        return archived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.archived
     *
     * @param archived the value for user_.archived
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setArchived(Boolean archived) {
        this.archived = archived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.default_user
     *
     * @return the value of user_.default_user
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Boolean getDefaultUser() {
        return defaultUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.default_user
     *
     * @param defaultUser the value for user_.default_user
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setDefaultUser(Boolean defaultUser) {
        this.defaultUser = defaultUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.createby
     *
     * @return the value of user_.createby
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.createby
     *
     * @param createby the value for user_.createby
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.createdate
     *
     * @return the value of user_.createdate
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.createdate
     *
     * @param createdate the value for user_.createdate
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.updateby
     *
     * @return the value of user_.updateby
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.updateby
     *
     * @param updateby the value for user_.updateby
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.updatedate
     *
     * @return the value of user_.updatedate
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.updatedate
     *
     * @param updatedate the value for user_.updatedate
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.dispname
     *
     * @return the value of user_.dispname
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public String getDispname() {
        return dispname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.dispname
     *
     * @param dispname the value for user_.dispname
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setDispname(String dispname) {
        this.dispname = dispname == null ? null : dispname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.truename
     *
     * @return the value of user_.truename
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.truename
     *
     * @param truename the value for user_.truename
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setTruename(String truename) {
        this.truename = truename == null ? null : truename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.isshownickname
     *
     * @return the value of user_.isshownickname
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Integer getIsshownickname() {
        return isshownickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.isshownickname
     *
     * @param isshownickname the value for user_.isshownickname
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setIsshownickname(Integer isshownickname) {
        this.isshownickname = isshownickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.sex
     *
     * @return the value of user_.sex
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.sex
     *
     * @param sex the value for user_.sex
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.superioruserid
     *
     * @return the value of user_.superioruserid
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Integer getSuperioruserid() {
        return superioruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.superioruserid
     *
     * @param superioruserid the value for user_.superioruserid
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setSuperioruserid(Integer superioruserid) {
        this.superioruserid = superioruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.securitypass
     *
     * @return the value of user_.securitypass
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public String getSecuritypass() {
        return securitypass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.securitypass
     *
     * @param securitypass the value for user_.securitypass
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setSecuritypass(String securitypass) {
        this.securitypass = securitypass == null ? null : securitypass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.securitylevel
     *
     * @return the value of user_.securitylevel
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Integer getSecuritylevel() {
        return securitylevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.securitylevel
     *
     * @param securitylevel the value for user_.securitylevel
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setSecuritylevel(Integer securitylevel) {
        this.securitylevel = securitylevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.authstatus
     *
     * @return the value of user_.authstatus
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Integer getAuthstatus() {
        return authstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.authstatus
     *
     * @param authstatus the value for user_.authstatus
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setAuthstatus(Integer authstatus) {
        this.authstatus = authstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.status
     *
     * @return the value of user_.status
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.status
     *
     * @param status the value for user_.status
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	@Override
	public String toString() {
		return "User_ [id=" + id + ", guid=" + guid + ", username=" + username + ", password=" + password
				+ ", nickname=" + nickname + ", phone=" + phone + ", email=" + email + ", logourl=" + logourl
				+ ", lastLoginTime=" + lastLoginTime + ", createTime=" + createTime + ", version=" + version
				+ ", smscode=" + smscode + ", archived=" + archived + ", defaultUser=" + defaultUser + ", createby="
				+ createby + ", createdate=" + createdate + ", updateby=" + updateby + ", updatedate=" + updatedate
				+ ", dispname=" + dispname + ", truename=" + truename + ", isshownickname=" + isshownickname + ", sex="
				+ sex + ", superioruserid=" + superioruserid + ", securitypass=" + securitypass + ", securitylevel="
				+ securitylevel + ", authstatus=" + authstatus + ", status=" + status + "]";
	}
    
}