package com.xiben.sso.site.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class User_Example implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public User_Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGuidIsNull() {
            addCriterion("guid is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("guid is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("guid =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("guid <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("guid >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("guid >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("guid <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("guid <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("guid like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("guid not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("guid in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("guid not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("guid between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("guid not between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andLogourlIsNull() {
            addCriterion("logourl is null");
            return (Criteria) this;
        }

        public Criteria andLogourlIsNotNull() {
            addCriterion("logourl is not null");
            return (Criteria) this;
        }

        public Criteria andLogourlEqualTo(String value) {
            addCriterion("logourl =", value, "logourl");
            return (Criteria) this;
        }

        public Criteria andLogourlNotEqualTo(String value) {
            addCriterion("logourl <>", value, "logourl");
            return (Criteria) this;
        }

        public Criteria andLogourlGreaterThan(String value) {
            addCriterion("logourl >", value, "logourl");
            return (Criteria) this;
        }

        public Criteria andLogourlGreaterThanOrEqualTo(String value) {
            addCriterion("logourl >=", value, "logourl");
            return (Criteria) this;
        }

        public Criteria andLogourlLessThan(String value) {
            addCriterion("logourl <", value, "logourl");
            return (Criteria) this;
        }

        public Criteria andLogourlLessThanOrEqualTo(String value) {
            addCriterion("logourl <=", value, "logourl");
            return (Criteria) this;
        }

        public Criteria andLogourlLike(String value) {
            addCriterion("logourl like", value, "logourl");
            return (Criteria) this;
        }

        public Criteria andLogourlNotLike(String value) {
            addCriterion("logourl not like", value, "logourl");
            return (Criteria) this;
        }

        public Criteria andLogourlIn(List<String> values) {
            addCriterion("logourl in", values, "logourl");
            return (Criteria) this;
        }

        public Criteria andLogourlNotIn(List<String> values) {
            addCriterion("logourl not in", values, "logourl");
            return (Criteria) this;
        }

        public Criteria andLogourlBetween(String value1, String value2) {
            addCriterion("logourl between", value1, value2, "logourl");
            return (Criteria) this;
        }

        public Criteria andLogourlNotBetween(String value1, String value2) {
            addCriterion("logourl not between", value1, value2, "logourl");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNull() {
            addCriterion("last_login_time is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNotNull() {
            addCriterion("last_login_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeEqualTo(Date value) {
            addCriterion("last_login_time =", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotEqualTo(Date value) {
            addCriterion("last_login_time <>", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThan(Date value) {
            addCriterion("last_login_time >", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_login_time >=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThan(Date value) {
            addCriterion("last_login_time <", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_login_time <=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIn(List<Date> values) {
            addCriterion("last_login_time in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotIn(List<Date> values) {
            addCriterion("last_login_time not in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeBetween(Date value1, Date value2) {
            addCriterion("last_login_time between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_login_time not between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andSmscodeIsNull() {
            addCriterion("smscode is null");
            return (Criteria) this;
        }

        public Criteria andSmscodeIsNotNull() {
            addCriterion("smscode is not null");
            return (Criteria) this;
        }

        public Criteria andSmscodeEqualTo(String value) {
            addCriterion("smscode =", value, "smscode");
            return (Criteria) this;
        }

        public Criteria andSmscodeNotEqualTo(String value) {
            addCriterion("smscode <>", value, "smscode");
            return (Criteria) this;
        }

        public Criteria andSmscodeGreaterThan(String value) {
            addCriterion("smscode >", value, "smscode");
            return (Criteria) this;
        }

        public Criteria andSmscodeGreaterThanOrEqualTo(String value) {
            addCriterion("smscode >=", value, "smscode");
            return (Criteria) this;
        }

        public Criteria andSmscodeLessThan(String value) {
            addCriterion("smscode <", value, "smscode");
            return (Criteria) this;
        }

        public Criteria andSmscodeLessThanOrEqualTo(String value) {
            addCriterion("smscode <=", value, "smscode");
            return (Criteria) this;
        }

        public Criteria andSmscodeLike(String value) {
            addCriterion("smscode like", value, "smscode");
            return (Criteria) this;
        }

        public Criteria andSmscodeNotLike(String value) {
            addCriterion("smscode not like", value, "smscode");
            return (Criteria) this;
        }

        public Criteria andSmscodeIn(List<String> values) {
            addCriterion("smscode in", values, "smscode");
            return (Criteria) this;
        }

        public Criteria andSmscodeNotIn(List<String> values) {
            addCriterion("smscode not in", values, "smscode");
            return (Criteria) this;
        }

        public Criteria andSmscodeBetween(String value1, String value2) {
            addCriterion("smscode between", value1, value2, "smscode");
            return (Criteria) this;
        }

        public Criteria andSmscodeNotBetween(String value1, String value2) {
            addCriterion("smscode not between", value1, value2, "smscode");
            return (Criteria) this;
        }

        public Criteria andArchivedIsNull() {
            addCriterion("archived is null");
            return (Criteria) this;
        }

        public Criteria andArchivedIsNotNull() {
            addCriterion("archived is not null");
            return (Criteria) this;
        }

        public Criteria andArchivedEqualTo(Boolean value) {
            addCriterion("archived =", value, "archived");
            return (Criteria) this;
        }

        public Criteria andArchivedNotEqualTo(Boolean value) {
            addCriterion("archived <>", value, "archived");
            return (Criteria) this;
        }

        public Criteria andArchivedGreaterThan(Boolean value) {
            addCriterion("archived >", value, "archived");
            return (Criteria) this;
        }

        public Criteria andArchivedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("archived >=", value, "archived");
            return (Criteria) this;
        }

        public Criteria andArchivedLessThan(Boolean value) {
            addCriterion("archived <", value, "archived");
            return (Criteria) this;
        }

        public Criteria andArchivedLessThanOrEqualTo(Boolean value) {
            addCriterion("archived <=", value, "archived");
            return (Criteria) this;
        }

        public Criteria andArchivedIn(List<Boolean> values) {
            addCriterion("archived in", values, "archived");
            return (Criteria) this;
        }

        public Criteria andArchivedNotIn(List<Boolean> values) {
            addCriterion("archived not in", values, "archived");
            return (Criteria) this;
        }

        public Criteria andArchivedBetween(Boolean value1, Boolean value2) {
            addCriterion("archived between", value1, value2, "archived");
            return (Criteria) this;
        }

        public Criteria andArchivedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("archived not between", value1, value2, "archived");
            return (Criteria) this;
        }

        public Criteria andDefaultUserIsNull() {
            addCriterion("default_user is null");
            return (Criteria) this;
        }

        public Criteria andDefaultUserIsNotNull() {
            addCriterion("default_user is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultUserEqualTo(Boolean value) {
            addCriterion("default_user =", value, "defaultUser");
            return (Criteria) this;
        }

        public Criteria andDefaultUserNotEqualTo(Boolean value) {
            addCriterion("default_user <>", value, "defaultUser");
            return (Criteria) this;
        }

        public Criteria andDefaultUserGreaterThan(Boolean value) {
            addCriterion("default_user >", value, "defaultUser");
            return (Criteria) this;
        }

        public Criteria andDefaultUserGreaterThanOrEqualTo(Boolean value) {
            addCriterion("default_user >=", value, "defaultUser");
            return (Criteria) this;
        }

        public Criteria andDefaultUserLessThan(Boolean value) {
            addCriterion("default_user <", value, "defaultUser");
            return (Criteria) this;
        }

        public Criteria andDefaultUserLessThanOrEqualTo(Boolean value) {
            addCriterion("default_user <=", value, "defaultUser");
            return (Criteria) this;
        }

        public Criteria andDefaultUserIn(List<Boolean> values) {
            addCriterion("default_user in", values, "defaultUser");
            return (Criteria) this;
        }

        public Criteria andDefaultUserNotIn(List<Boolean> values) {
            addCriterion("default_user not in", values, "defaultUser");
            return (Criteria) this;
        }

        public Criteria andDefaultUserBetween(Boolean value1, Boolean value2) {
            addCriterion("default_user between", value1, value2, "defaultUser");
            return (Criteria) this;
        }

        public Criteria andDefaultUserNotBetween(Boolean value1, Boolean value2) {
            addCriterion("default_user not between", value1, value2, "defaultUser");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("createby is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("createby is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(Integer value) {
            addCriterion("createby =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(Integer value) {
            addCriterion("createby <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(Integer value) {
            addCriterion("createby >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(Integer value) {
            addCriterion("createby >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(Integer value) {
            addCriterion("createby <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(Integer value) {
            addCriterion("createby <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<Integer> values) {
            addCriterion("createby in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<Integer> values) {
            addCriterion("createby not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(Integer value1, Integer value2) {
            addCriterion("createby between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(Integer value1, Integer value2) {
            addCriterion("createby not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createdate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createdate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createdate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createdate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createdate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createdate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createdate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createdate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createdate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createdate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createdate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createdate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNull() {
            addCriterion("updateby is null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNotNull() {
            addCriterion("updateby is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyEqualTo(Integer value) {
            addCriterion("updateby =", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotEqualTo(Integer value) {
            addCriterion("updateby <>", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThan(Integer value) {
            addCriterion("updateby >", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThanOrEqualTo(Integer value) {
            addCriterion("updateby >=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThan(Integer value) {
            addCriterion("updateby <", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThanOrEqualTo(Integer value) {
            addCriterion("updateby <=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIn(List<Integer> values) {
            addCriterion("updateby in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotIn(List<Integer> values) {
            addCriterion("updateby not in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyBetween(Integer value1, Integer value2) {
            addCriterion("updateby between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotBetween(Integer value1, Integer value2) {
            addCriterion("updateby not between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNull() {
            addCriterion("updatedate is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNotNull() {
            addCriterion("updatedate is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateEqualTo(Date value) {
            addCriterion("updatedate =", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotEqualTo(Date value) {
            addCriterion("updatedate <>", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThan(Date value) {
            addCriterion("updatedate >", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("updatedate >=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThan(Date value) {
            addCriterion("updatedate <", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThanOrEqualTo(Date value) {
            addCriterion("updatedate <=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIn(List<Date> values) {
            addCriterion("updatedate in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotIn(List<Date> values) {
            addCriterion("updatedate not in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateBetween(Date value1, Date value2) {
            addCriterion("updatedate between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotBetween(Date value1, Date value2) {
            addCriterion("updatedate not between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andDispnameIsNull() {
            addCriterion("dispname is null");
            return (Criteria) this;
        }

        public Criteria andDispnameIsNotNull() {
            addCriterion("dispname is not null");
            return (Criteria) this;
        }

        public Criteria andDispnameEqualTo(String value) {
            addCriterion("dispname =", value, "dispname");
            return (Criteria) this;
        }

        public Criteria andDispnameNotEqualTo(String value) {
            addCriterion("dispname <>", value, "dispname");
            return (Criteria) this;
        }

        public Criteria andDispnameGreaterThan(String value) {
            addCriterion("dispname >", value, "dispname");
            return (Criteria) this;
        }

        public Criteria andDispnameGreaterThanOrEqualTo(String value) {
            addCriterion("dispname >=", value, "dispname");
            return (Criteria) this;
        }

        public Criteria andDispnameLessThan(String value) {
            addCriterion("dispname <", value, "dispname");
            return (Criteria) this;
        }

        public Criteria andDispnameLessThanOrEqualTo(String value) {
            addCriterion("dispname <=", value, "dispname");
            return (Criteria) this;
        }

        public Criteria andDispnameLike(String value) {
            addCriterion("dispname like", value, "dispname");
            return (Criteria) this;
        }

        public Criteria andDispnameNotLike(String value) {
            addCriterion("dispname not like", value, "dispname");
            return (Criteria) this;
        }

        public Criteria andDispnameIn(List<String> values) {
            addCriterion("dispname in", values, "dispname");
            return (Criteria) this;
        }

        public Criteria andDispnameNotIn(List<String> values) {
            addCriterion("dispname not in", values, "dispname");
            return (Criteria) this;
        }

        public Criteria andDispnameBetween(String value1, String value2) {
            addCriterion("dispname between", value1, value2, "dispname");
            return (Criteria) this;
        }

        public Criteria andDispnameNotBetween(String value1, String value2) {
            addCriterion("dispname not between", value1, value2, "dispname");
            return (Criteria) this;
        }

        public Criteria andTruenameIsNull() {
            addCriterion("truename is null");
            return (Criteria) this;
        }

        public Criteria andTruenameIsNotNull() {
            addCriterion("truename is not null");
            return (Criteria) this;
        }

        public Criteria andTruenameEqualTo(String value) {
            addCriterion("truename =", value, "truename");
            return (Criteria) this;
        }

        public Criteria andTruenameNotEqualTo(String value) {
            addCriterion("truename <>", value, "truename");
            return (Criteria) this;
        }

        public Criteria andTruenameGreaterThan(String value) {
            addCriterion("truename >", value, "truename");
            return (Criteria) this;
        }

        public Criteria andTruenameGreaterThanOrEqualTo(String value) {
            addCriterion("truename >=", value, "truename");
            return (Criteria) this;
        }

        public Criteria andTruenameLessThan(String value) {
            addCriterion("truename <", value, "truename");
            return (Criteria) this;
        }

        public Criteria andTruenameLessThanOrEqualTo(String value) {
            addCriterion("truename <=", value, "truename");
            return (Criteria) this;
        }

        public Criteria andTruenameLike(String value) {
            addCriterion("truename like", value, "truename");
            return (Criteria) this;
        }

        public Criteria andTruenameNotLike(String value) {
            addCriterion("truename not like", value, "truename");
            return (Criteria) this;
        }

        public Criteria andTruenameIn(List<String> values) {
            addCriterion("truename in", values, "truename");
            return (Criteria) this;
        }

        public Criteria andTruenameNotIn(List<String> values) {
            addCriterion("truename not in", values, "truename");
            return (Criteria) this;
        }

        public Criteria andTruenameBetween(String value1, String value2) {
            addCriterion("truename between", value1, value2, "truename");
            return (Criteria) this;
        }

        public Criteria andTruenameNotBetween(String value1, String value2) {
            addCriterion("truename not between", value1, value2, "truename");
            return (Criteria) this;
        }

        public Criteria andIsshownicknameIsNull() {
            addCriterion("isshownickname is null");
            return (Criteria) this;
        }

        public Criteria andIsshownicknameIsNotNull() {
            addCriterion("isshownickname is not null");
            return (Criteria) this;
        }

        public Criteria andIsshownicknameEqualTo(Integer value) {
            addCriterion("isshownickname =", value, "isshownickname");
            return (Criteria) this;
        }

        public Criteria andIsshownicknameNotEqualTo(Integer value) {
            addCriterion("isshownickname <>", value, "isshownickname");
            return (Criteria) this;
        }

        public Criteria andIsshownicknameGreaterThan(Integer value) {
            addCriterion("isshownickname >", value, "isshownickname");
            return (Criteria) this;
        }

        public Criteria andIsshownicknameGreaterThanOrEqualTo(Integer value) {
            addCriterion("isshownickname >=", value, "isshownickname");
            return (Criteria) this;
        }

        public Criteria andIsshownicknameLessThan(Integer value) {
            addCriterion("isshownickname <", value, "isshownickname");
            return (Criteria) this;
        }

        public Criteria andIsshownicknameLessThanOrEqualTo(Integer value) {
            addCriterion("isshownickname <=", value, "isshownickname");
            return (Criteria) this;
        }

        public Criteria andIsshownicknameIn(List<Integer> values) {
            addCriterion("isshownickname in", values, "isshownickname");
            return (Criteria) this;
        }

        public Criteria andIsshownicknameNotIn(List<Integer> values) {
            addCriterion("isshownickname not in", values, "isshownickname");
            return (Criteria) this;
        }

        public Criteria andIsshownicknameBetween(Integer value1, Integer value2) {
            addCriterion("isshownickname between", value1, value2, "isshownickname");
            return (Criteria) this;
        }

        public Criteria andIsshownicknameNotBetween(Integer value1, Integer value2) {
            addCriterion("isshownickname not between", value1, value2, "isshownickname");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Integer value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Integer value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Integer value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Integer value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Integer value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Integer> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Integer> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Integer value1, Integer value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Integer value1, Integer value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSuperioruseridIsNull() {
            addCriterion("superioruserid is null");
            return (Criteria) this;
        }

        public Criteria andSuperioruseridIsNotNull() {
            addCriterion("superioruserid is not null");
            return (Criteria) this;
        }

        public Criteria andSuperioruseridEqualTo(Integer value) {
            addCriterion("superioruserid =", value, "superioruserid");
            return (Criteria) this;
        }

        public Criteria andSuperioruseridNotEqualTo(Integer value) {
            addCriterion("superioruserid <>", value, "superioruserid");
            return (Criteria) this;
        }

        public Criteria andSuperioruseridGreaterThan(Integer value) {
            addCriterion("superioruserid >", value, "superioruserid");
            return (Criteria) this;
        }

        public Criteria andSuperioruseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("superioruserid >=", value, "superioruserid");
            return (Criteria) this;
        }

        public Criteria andSuperioruseridLessThan(Integer value) {
            addCriterion("superioruserid <", value, "superioruserid");
            return (Criteria) this;
        }

        public Criteria andSuperioruseridLessThanOrEqualTo(Integer value) {
            addCriterion("superioruserid <=", value, "superioruserid");
            return (Criteria) this;
        }

        public Criteria andSuperioruseridIn(List<Integer> values) {
            addCriterion("superioruserid in", values, "superioruserid");
            return (Criteria) this;
        }

        public Criteria andSuperioruseridNotIn(List<Integer> values) {
            addCriterion("superioruserid not in", values, "superioruserid");
            return (Criteria) this;
        }

        public Criteria andSuperioruseridBetween(Integer value1, Integer value2) {
            addCriterion("superioruserid between", value1, value2, "superioruserid");
            return (Criteria) this;
        }

        public Criteria andSuperioruseridNotBetween(Integer value1, Integer value2) {
            addCriterion("superioruserid not between", value1, value2, "superioruserid");
            return (Criteria) this;
        }

        public Criteria andSecuritypassIsNull() {
            addCriterion("securitypass is null");
            return (Criteria) this;
        }

        public Criteria andSecuritypassIsNotNull() {
            addCriterion("securitypass is not null");
            return (Criteria) this;
        }

        public Criteria andSecuritypassEqualTo(String value) {
            addCriterion("securitypass =", value, "securitypass");
            return (Criteria) this;
        }

        public Criteria andSecuritypassNotEqualTo(String value) {
            addCriterion("securitypass <>", value, "securitypass");
            return (Criteria) this;
        }

        public Criteria andSecuritypassGreaterThan(String value) {
            addCriterion("securitypass >", value, "securitypass");
            return (Criteria) this;
        }

        public Criteria andSecuritypassGreaterThanOrEqualTo(String value) {
            addCriterion("securitypass >=", value, "securitypass");
            return (Criteria) this;
        }

        public Criteria andSecuritypassLessThan(String value) {
            addCriterion("securitypass <", value, "securitypass");
            return (Criteria) this;
        }

        public Criteria andSecuritypassLessThanOrEqualTo(String value) {
            addCriterion("securitypass <=", value, "securitypass");
            return (Criteria) this;
        }

        public Criteria andSecuritypassLike(String value) {
            addCriterion("securitypass like", value, "securitypass");
            return (Criteria) this;
        }

        public Criteria andSecuritypassNotLike(String value) {
            addCriterion("securitypass not like", value, "securitypass");
            return (Criteria) this;
        }

        public Criteria andSecuritypassIn(List<String> values) {
            addCriterion("securitypass in", values, "securitypass");
            return (Criteria) this;
        }

        public Criteria andSecuritypassNotIn(List<String> values) {
            addCriterion("securitypass not in", values, "securitypass");
            return (Criteria) this;
        }

        public Criteria andSecuritypassBetween(String value1, String value2) {
            addCriterion("securitypass between", value1, value2, "securitypass");
            return (Criteria) this;
        }

        public Criteria andSecuritypassNotBetween(String value1, String value2) {
            addCriterion("securitypass not between", value1, value2, "securitypass");
            return (Criteria) this;
        }

        public Criteria andSecuritylevelIsNull() {
            addCriterion("securitylevel is null");
            return (Criteria) this;
        }

        public Criteria andSecuritylevelIsNotNull() {
            addCriterion("securitylevel is not null");
            return (Criteria) this;
        }

        public Criteria andSecuritylevelEqualTo(Integer value) {
            addCriterion("securitylevel =", value, "securitylevel");
            return (Criteria) this;
        }

        public Criteria andSecuritylevelNotEqualTo(Integer value) {
            addCriterion("securitylevel <>", value, "securitylevel");
            return (Criteria) this;
        }

        public Criteria andSecuritylevelGreaterThan(Integer value) {
            addCriterion("securitylevel >", value, "securitylevel");
            return (Criteria) this;
        }

        public Criteria andSecuritylevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("securitylevel >=", value, "securitylevel");
            return (Criteria) this;
        }

        public Criteria andSecuritylevelLessThan(Integer value) {
            addCriterion("securitylevel <", value, "securitylevel");
            return (Criteria) this;
        }

        public Criteria andSecuritylevelLessThanOrEqualTo(Integer value) {
            addCriterion("securitylevel <=", value, "securitylevel");
            return (Criteria) this;
        }

        public Criteria andSecuritylevelIn(List<Integer> values) {
            addCriterion("securitylevel in", values, "securitylevel");
            return (Criteria) this;
        }

        public Criteria andSecuritylevelNotIn(List<Integer> values) {
            addCriterion("securitylevel not in", values, "securitylevel");
            return (Criteria) this;
        }

        public Criteria andSecuritylevelBetween(Integer value1, Integer value2) {
            addCriterion("securitylevel between", value1, value2, "securitylevel");
            return (Criteria) this;
        }

        public Criteria andSecuritylevelNotBetween(Integer value1, Integer value2) {
            addCriterion("securitylevel not between", value1, value2, "securitylevel");
            return (Criteria) this;
        }

        public Criteria andAuthstatusIsNull() {
            addCriterion("authstatus is null");
            return (Criteria) this;
        }

        public Criteria andAuthstatusIsNotNull() {
            addCriterion("authstatus is not null");
            return (Criteria) this;
        }

        public Criteria andAuthstatusEqualTo(Integer value) {
            addCriterion("authstatus =", value, "authstatus");
            return (Criteria) this;
        }

        public Criteria andAuthstatusNotEqualTo(Integer value) {
            addCriterion("authstatus <>", value, "authstatus");
            return (Criteria) this;
        }

        public Criteria andAuthstatusGreaterThan(Integer value) {
            addCriterion("authstatus >", value, "authstatus");
            return (Criteria) this;
        }

        public Criteria andAuthstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("authstatus >=", value, "authstatus");
            return (Criteria) this;
        }

        public Criteria andAuthstatusLessThan(Integer value) {
            addCriterion("authstatus <", value, "authstatus");
            return (Criteria) this;
        }

        public Criteria andAuthstatusLessThanOrEqualTo(Integer value) {
            addCriterion("authstatus <=", value, "authstatus");
            return (Criteria) this;
        }

        public Criteria andAuthstatusIn(List<Integer> values) {
            addCriterion("authstatus in", values, "authstatus");
            return (Criteria) this;
        }

        public Criteria andAuthstatusNotIn(List<Integer> values) {
            addCriterion("authstatus not in", values, "authstatus");
            return (Criteria) this;
        }

        public Criteria andAuthstatusBetween(Integer value1, Integer value2) {
            addCriterion("authstatus between", value1, value2, "authstatus");
            return (Criteria) this;
        }

        public Criteria andAuthstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("authstatus not between", value1, value2, "authstatus");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 02 08:23:00 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}