package com.xiben.sso.site.dao;

import com.xiben.sso.site.bean.OauthClientDetails;
import com.xiben.sso.site.bean.OauthClientDetailsExample;
import com.xiben.sso.site.bean.OauthClientDetailsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface OauthClientDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    int countByExample(OauthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    int deleteByExample(OauthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    int deleteByPrimaryKey(String clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    int insert(OauthClientDetailsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    int insertSelective(OauthClientDetailsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    List<OauthClientDetailsWithBLOBs> selectByExampleWithBLOBs(OauthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    List<OauthClientDetails> selectByExample(OauthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    OauthClientDetailsWithBLOBs selectByPrimaryKey(String clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") OauthClientDetailsWithBLOBs record, @Param("example") OauthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") OauthClientDetailsWithBLOBs record, @Param("example") OauthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    int updateByExample(@Param("record") OauthClientDetails record, @Param("example") OauthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    int updateByPrimaryKeySelective(OauthClientDetailsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(OauthClientDetailsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Mon Nov 06 23:58:26 CST 2017
     */
    int updateByPrimaryKey(OauthClientDetails record);
}