package com.xiben.sso.site.dao;

import com.xiben.sso.site.bean.OauthClientUser;
import com.xiben.sso.site.bean.OauthClientUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface OauthClientUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_user
     *
     * @mbggenerated Tue Nov 07 09:17:23 CST 2017
     */
    int countByExample(OauthClientUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_user
     *
     * @mbggenerated Tue Nov 07 09:17:23 CST 2017
     */
    int deleteByExample(OauthClientUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_user
     *
     * @mbggenerated Tue Nov 07 09:17:23 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_user
     *
     * @mbggenerated Tue Nov 07 09:17:23 CST 2017
     */
    int insert(OauthClientUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_user
     *
     * @mbggenerated Tue Nov 07 09:17:23 CST 2017
     */
    int insertSelective(OauthClientUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_user
     *
     * @mbggenerated Tue Nov 07 09:17:23 CST 2017
     */
    List<OauthClientUser> selectByExample(OauthClientUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_user
     *
     * @mbggenerated Tue Nov 07 09:17:23 CST 2017
     */
    OauthClientUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_user
     *
     * @mbggenerated Tue Nov 07 09:17:23 CST 2017
     */
    int updateByExampleSelective(@Param("record") OauthClientUser record, @Param("example") OauthClientUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_user
     *
     * @mbggenerated Tue Nov 07 09:17:23 CST 2017
     */
    int updateByExample(@Param("record") OauthClientUser record, @Param("example") OauthClientUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_user
     *
     * @mbggenerated Tue Nov 07 09:17:23 CST 2017
     */
    int updateByPrimaryKeySelective(OauthClientUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_user
     *
     * @mbggenerated Tue Nov 07 09:17:23 CST 2017
     */
    int updateByPrimaryKey(OauthClientUser record);


	List<OauthClientUser> queryByClientIdAndUserId(OauthClientUser param);

	
}