package com.xiben.sso.site.dao;

import com.xiben.sso.site.bean.User_;
import com.xiben.sso.site.bean.User_Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface User_Mapper {
	
	
	 User_ queryByUsername(String username);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    int countByExample(User_Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    int deleteByExample(User_Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    int insert(User_ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    int insertSelective(User_ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    List<User_> selectByExample(User_Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    User_ selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") User_ record, @Param("example") User_Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    int updateByExample(@Param("record") User_ record, @Param("example") User_Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    int updateByPrimaryKeySelective(User_ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Thu Nov 02 08:23:00 CST 2017
     */
    int updateByPrimaryKey(User_ record);
}